version: '2'

services:
  redis:
    image: redis
    ports:
      - "6379:6379"
    command: redis-server

  app:
    build: .
    command: python manage.py runserver --host 0.0.0.0
    volumes:
      - .:/var/www/apium
    ports:
      - "5000:5000"
    network_mode: "host"

  celery:
    build: .
    command: python runcelery.py -A apium.tasks.jobs worker
    volumes:
      - .:/var/www/apium
    network_mode: "host"
